[package]
name = "day-02"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.12.0"
rayon = "1.8.0"
regex = "1.10.2"

[[bin]]
name = "p1"
path = "src/p1.rs"

[[bin]]
name = "p2"
path = "src/p2.rs"

